### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/flutterx100#14]
Improve the readme to display the overview of this project. You can display the code of conduct, License, or Sourceror profiles.

**Comment by AvinashMahanthi** [comment]
I will work on the Code of Conduct, I will make that in a clean way, so I can take this, plz assign

**Comment by himanshusharma89** [comment]
@AvinashMahanthi Code of Conduct is already added, you can modify the README by embedding the Code of Conduct in it. You can refer to README of the Blog App.

**Comment by AvinashMahanthi** [comment]
Ok I will embed that, please assign this to me @himanshusharma89

**Comment by AvinashMahanthi** [comment]
@himanshusharma89 Please check the pl #28, I had done according to your request
