### ISSUE TITLE
Issue Labeler Workflow

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/flutterx100#20]
create a GitHub Action which will automatically label all the new issues created with the Hacktoberfest label.

**Comment by rahullli** [comment]
I would like to work on this issue , can you please tell me more what issue is it and what workflow is there ?

**Comment by himanshusharma89** [comment]
Hey @rahullli, you need to create a GitHub Action which will automatically label all the new issues created with the Hacktoberfest label.

**Comment by Mastersam07** [comment]
@rahullli @himanshusharma89 Is this still worked on? I could send a PR attending to this

**Comment by himanshusharma89** [comment]
@rahullli Are you facing an issue or couldn't make a PR? I can pass this issue to @Mastersam07.

**Comment by himanshusharma89** [comment]
@Mastersam07 Can you take over this issue? I'll assign it to you

**Comment by Mastersam07** [comment]
Sure. Assign to me
