### ISSUE TITLE
FAQ Page

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/flutterx100#21]
Refer to https://www.100daysofcode.com/faq/ for the content

**Comment by HeyKos** [comment]
@himanshusharma89 I'd love to help you out with this issue. I've forked the repo, read the contributing guide and code of conduct. If you're okay with me hopping on this please assign me to the issue. I am using VSCode for development, and upon loading the project it has made some IDE driven modifications to the `pubspec.lock`, `Debug.xcconfig`, `Release.xcconfig`. It also added an iOS Podfile. So if this is something you're comfortable with me working on I'd appreciate some collaboration on how to handle these discrepancies as well.

**Comment by himanshusharma89** [comment]
Hey @HeyKos, it's good to know that you are contributing to this project and about the other files being added/updated, it is all fine until we face an issue with our web app 😅. So its good to have you here and I am assigning this issue to you.

**Comment by HeyKos** [comment]
Awesome! @himanshusharma89 Do you have any preference or guidelines to the UI of the FAQs? I can scaffold something initially, and send some screenshots to discuss around if that's how you want to collaborate.

**Comment by HeyKos** [comment]
Another question @himanshusharma89 . Where do you want the user to access the FAQs from? Will that be part of the bottom bar navigation? If so we're running low on real estate 😄 . If you just want me to scaffold out the page, and figure out where it goes later that's fine too.

**Comment by himanshusharma89** [comment]
@HeyKos, the FAQ will be situated int the topbar in medium screen and large screen. For the small screen, you can add it in the bottom bar stack. About the content, you can refer to https://www.100daysofcode.com/faq/ and for UI you can follow up the current UI and create something.

**Comment by HeyKos** [comment]
@himanshusharma89 I have a question about the desired UX for sub pages. There was no existing routing solution configured, so I started going down the path of defining routes in `main.dart`. However this creates a bit of a strange behavior for how the user is directed to another page. By using `Navigator.pushNamed` I am able to navigate the user from the dashboard to an FAQ page that uses the same logic to determine whether to render a top bar or bottom bar based on the screen size. The experience of navigating is a bit jarring. So my question to you is, is routing the way to go, or should we be dynamically loading widgets for page content when top/bottom bar items are clicked/tapped? I am leaning more this way, but obviously that limits the web experience which would benefit from having an actual route that a user could specify in the browser address bar, and it would take them to the appropriate page. 

I have also not had much experience using flutter for the web, and it looks like you have it configured to run on the web, but I am not seeing how that is configured. I'd love to be able to debug in a browser if that is an experience we're building for. Is this going to be launched as native apps for iOS and Android, or is it supposed to be a website (or both)? I want to make sure I am building and testing in the environment you're intending to launch on. If you are building primarily for the web, I'd benefit from understanding how you have that configured. It seems different from the [Flutter docs](https://flutter.dev/docs/get-started/web).

**Comment by HeyKos** [comment]
@himanshusharma89 here is an example of the navigation when using the `Navigator` API.
![FAQs](https://user-images.githubusercontent.com/5178698/95018168-f0e79000-062b-11eb-93db-379f2f75b928.gif)

**Comment by himanshusharma89** [comment]
Hi @HeyKos, this project is aimed only for the web(responsive website). And about ios and android, there is going to be a separate project for that. And I created this project from Flutter extension in VS Code and then I enabled web in it. And for web-like experience, we can use `PageView` for that or we can go along your second method of dynamically fetching the widgets (but it might affect the web experience).

**Comment by HeyKos** [comment]
@himanshusharma89 how do you run this in a browser for interactive debugging? I don't have that config in my vscode launch settings.

**Comment by himanshusharma89** [comment]
@HeyKos, change your channel, do flutter upgrade and run the app, it'll prompt to run the app with Chrome, Edge or Web Server (It needs Dart Debug Extension)

**Comment by himanshusharma89** [comment]
Hi @HeyKos, any update?

**Comment by HeyKos** [comment]
Yes @himanshusharma89 . I was able to target the dev channel and enable web. From there I was able to scaffold a `PageView` and wire it up to switch pages when the FAQs navigation item is tapped. My next steps are to add in the FAQs content you supplied, and then ensure that it works well in the mobile view as well. I plan on having a PR ready for your review this weekend.

Long term we should talk routing. I think the `PageView` approach will work, but a routing implementation using the `Navigator` could be a better long term solution. It would allow unique URL routes to map to content widgets without having to reload the frame of the site. Doing this would take a good bit of info, so we can cross that bridge later if you're interested in discussing.

**Comment by himanshusharma89** [comment]
Perfect @HeyKos, and yes I am interested in discussion. And I think for better understanding, you can create a new issue and point out everything related to navigation and web experience. We'll discuss it there.

**Comment by HeyKos** [comment]
@himanshusharma89 I've opened a PR with the changes to address this issue. Let me know if you need any revisions.

**Comment by himanshusharma89** [comment]
@HeyKos you can attach the screensots in the PR

**Comment by HeyKos** [comment]
I've added a mobile and desktop screenshot of the FAQs page to the PR. Let me know if you need anything else.
