### ISSUE TITLE
Guidance

### ISSUE THREAD

**Issue by anonymous887** [himanshusharma89/flutterx100#36]
Sir may I ask how did you learn so much about Flutter 
Did you follow some courses  or just documentation

I do try to go through the documentation but don't actually understand much
Please guide a bit @himanshusharma89

**Comment by himanshusharma89** [comment]
Hi @being-anonymous, I didn't follow any course, I just started created an app and looked into StackOverflow to earn about it. However, you should go with the resources provided on the official website. Also, learn dart before Flutter.

Additionally, raising an issue is not a way to contact me, you s should send me an email directly.
