### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/flutterx100#6]
You need to create an Aout page for the 100DaysOfFlutter Website following the current UI. Also refer to this: https://www.100daysofcode.com/about/ for the content of the website. Don't replicate the exact content, modify it for the Flutter Community.

**Comment by bibekpanda55** [comment]
I would like to work on this issue can you please elaborate?

**Comment by himanshusharma89** [comment]
Hey @bibekpanda55, check this:
You need to create an Aout page for the 100DaysOfFlutter Website following the current UI. Also refer to this: https://www.100daysofcode.com/about/ for the content of the website. Don't replicate the exact content, modify it for the Flutter Community.

**Comment by bibekpanda55** [comment]
Sure I can do that please assign it to me

**Comment by himanshusharma89** [comment]
Hi @bibekpanda55, any update?

**Comment by bibekpanda55** [comment]
Yeah It's almost done will commit by tomorrow

**Comment by himanshusharma89** [comment]
@bibekpanda55 Any update?

**Comment by ecrax** [comment]
Not sure if this is still relevant, but I will give it a try.
What version of Flutter are you working with?

**Comment by himanshusharma89** [comment]
@ecrax Channel beta, 1.22.1
